engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
