defaults: &defaults
  working_directory: ~/imojo
  docker:
  - image: circleci/openjdk:8-jdk
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
 build:
   <<: *defaults
   steps:
     - checkout

     - restore_cache:
         keys:
         - dependency-cache-{{ checksum "build.gradle" }}

     - run:
        name: Downloading dependencies
        command: gradle dependencies

     - save_cache:
         paths:
           - ~/.gradle
         key: dependency-cache-{{ checksum "build.gradle" }}

     - run:
        name: Running tests
        command: gradle test

     - run:
        name: Saving test results
        command: |
          mkdir -p ~/test-results/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/ \;
        when: always

     - store_test_results:
         path: ~/test-results

   release:
     <<: *defaults
     steps:
     - checkout
     - restore_cache:
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "instamojo-java/build.gradle" }}
     - run:
         name: Download Dependencies
         command: ./gradlew build
     - save_cache:
         paths:
         - ~/.gradle
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "instamojo-java/build.gradle" }}
     - run:
         name: Publish to Bintray
         command: ./gradlew bintrayUpload

workflows:
  version: 2
  build-and-release:
    jobs:
    - build:
        filters:
          # By default a build is only triggered on commits. Lets build for any tag too.
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/